2022-09-20 17:16:55,905 - fishTrade_main20220913.py[line:559] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-20 17:16:55,907 - fishTrade_main20220913.py[line:142] - INFO: 初始参数设置:symbol=eth_usdt highPrice=1700.0 lowPrice=1500.0  step_num=70.0
2022-09-20 17:16:58,410 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\test_gateAPI\marketHelper1005.py", line 226, in get_last_order_price
    d2 = uh.get_today()
NameError: name 'uh' is not defined

2022-09-20 17:17:00,411 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-20 17:17:02,858 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\test_gateAPI\marketHelper1005.py", line 226, in get_last_order_price
    d2 = uh.get_today()
NameError: name 'uh' is not defined

2022-09-20 17:17:04,859 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-20 17:17:07,482 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\test_gateAPI\marketHelper1005.py", line 226, in get_last_order_price
    d2 = uh.get_today()
NameError: name 'uh' is not defined

2022-09-20 17:17:09,482 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
