2022-09-19 00:01:17,179 - fishTrade_main20220913.py[line:554] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-19 00:01:17,180 - fishTrade_main20220913.py[line:142] - INFO: 初始参数设置:symbol=usdt_eth highPrice=1700.0 lowPrice=1500.0  step_num=70.0
2022-09-19 00:01:17,696 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:17,697 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:18,435 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:18,436 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:19,093 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:19,094 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:19,714 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:19,714 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:20,332 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:20,333 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:21,133 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:21,134 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:21,837 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:21,837 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:22,228 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 157, in strategy
    huobi_market = marketHelper.Market()
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 39, in __init__
    r = requests.request('GET', acfg.gateApi + prefix + url, headers=headers)
  File "D:\Python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Python\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "D:\Python\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "D:\Python\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Python\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "D:\Python\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Python\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

2022-09-19 00:01:22,232 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:22,909 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:22,910 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:23,416 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:23,416 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:23,894 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:23,894 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:24,580 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:24,580 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:25,205 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:25,205 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:27,107 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:27,107 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:01:27,757 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{0}_{1}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
AttributeError: 'NoneType' object has no attribute 'get'

2022-09-19 00:01:27,758 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
