2022-09-26 16:28:55,969 - fishTrade_main20220913.py[line:559] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-26 16:28:55,970 - fishTrade_main20220913.py[line:142] - INFO: 初始参数设置:symbol=eth_usdt highPrice=1700.0 lowPrice=1200.0  step_num=70.0
2022-09-26 16:28:59,636 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 239, in strategy
    buylots=pf.downRound(buylots,digits)
NameError: name 'pf' is not defined

2022-09-26 16:29:01,637 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-26 16:29:07,003 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 239, in strategy
    buylots=pf.downRound(buylots,digits)
NameError: name 'pf' is not defined

2022-09-26 16:29:09,004 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-26 16:29:12,380 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 239, in strategy
    buylots=pf.downRound(buylots,digits)
NameError: name 'pf' is not defined

2022-09-26 16:29:14,380 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-26 16:29:18,301 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 239, in strategy
    buylots=pf.downRound(buylots,digits)
NameError: name 'pf' is not defined

2022-09-26 16:29:20,302 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-26 16:29:23,737 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:/test_gateAPI/fishTrade_main20220913.py", line 239, in strategy
    buylots=pf.downRound(buylots,digits)
NameError: name 'pf' is not defined

2022-09-26 16:29:25,738 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
