2022-09-19 00:11:25,067 - fishTrade_main20220913.py[line:554] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-19 00:11:25,068 - fishTrade_main20220913.py[line:142] - INFO: 初始参数设置:symbol=usdt_eth highPrice=1700.0 lowPrice=1500.0  step_num=70.0
2022-09-19 00:11:27,226 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:27,227 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:30,309 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:30,310 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:31,609 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:31,610 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:32,700 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:32,701 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:33,795 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 157, in strategy
    huobi_market = marketHelper.Market()
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 39, in __init__
    r = requests.request('GET', acfg.gateApi + prefix + url, headers=headers)
  File "D:\Python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "D:\Python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
KeyboardInterrupt

2022-09-19 00:11:33,796 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:35,995 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:35,996 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:37,026 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:37,026 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:38,294 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:38,295 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:39,205 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:39,205 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:40,026 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:40,026 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:41,022 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:41,022 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:42,033 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:42,034 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:43,146 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:43,146 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:44,327 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:44,327 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:45,401 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:45,401 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:46,675 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:46,675 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:52,041 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:52,041 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:52,944 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:52,945 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:54,490 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:54,491 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:57,032 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:57,032 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:58,454 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:58,454 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:11:59,539 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:11:59,540 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:01,933 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:01,934 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:02,960 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:02,960 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:04,274 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:04,274 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:06,539 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:06,539 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:08,516 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:08,516 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:09,603 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:09,603 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:11,691 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:11,691 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:12,720 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:12,720 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:13,635 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:13,636 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:14,721 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:14,722 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:16,844 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:16,844 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:18,553 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:18,554 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:19,494 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:19,494 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:20,753 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:20,753 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:21,653 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:21,653 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:22,985 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:22,985 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:26,375 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:26,375 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:27,350 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:27,350 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:28,217 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:28,218 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:30,245 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:30,245 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:31,278 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:31,278 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:33,244 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:33,244 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:35,494 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:35,494 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:36,860 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:36,860 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:39,279 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:39,279 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:42,007 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:42,008 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:42,992 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:42,992 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:45,970 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:45,971 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:47,654 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:47,655 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:49,377 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:49,377 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:51,370 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:51,371 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:53,368 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:53,368 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:55,254 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:55,255 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:56,496 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:56,496 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:12:58,229 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:12:58,230 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:01,024 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:01,024 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:02,068 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:02,068 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:03,041 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:03,041 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:03,923 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:03,923 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:04,931 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:04,931 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:07,093 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:07,093 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:09,921 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:09,921 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:12,210 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:12,210 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:13,607 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:13,607 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:14,512 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:14,513 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:17,563 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:17,563 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:20,097 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:20,098 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:21,529 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:21,529 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:25,728 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:25,728 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:27,183 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:27,183 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-19 00:13:29,232 - fishTrade_main20220913.py[line:288] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 167, in strategy
    self.market_price_tick["{1}_{0}".format(self.base_cur, self.quote_cur)].get("asks")[0][0]
KeyError: 'eth_usdt'

2022-09-19 00:13:29,232 - fishTrade_main20220913.py[line:606] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
