2022-09-24 11:13:53,419 - fishTrade_main20220913.py[line:559] - INFO: 
                  ET网格智能交易系统3.0             
*************************版权声明***************************             
********************All Rights Reserved*********************             
软件开发：海易，需求订制联系微信：yyy99966             
优惠版：有效期30天，每分享一个好友，延长30天，10个延长一年

2022-09-24 11:13:53,419 - fishTrade_main20220913.py[line:142] - INFO: 初始参数设置:symbol=eth_usdt highPrice=1700.0 lowPrice=1500.0  step_num=70.0
2022-09-24 11:13:55,324 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:13:57,328 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:13:59,189 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:01,200 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:02,831 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:04,839 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:06,467 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:08,474 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:10,437 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:12,449 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:14,360 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:16,376 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:18,407 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:20,411 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:22,353 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:24,362 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:26,160 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:28,168 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:29,823 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:31,831 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:33,805 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:35,817 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:37,602 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:39,618 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:41,471 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

2022-09-24 11:14:43,487 - fishTrade_main20220913.py[line:612] - ERROR: 'Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')
2022-09-24 11:14:45,334 - fishTrade_main20220913.py[line:293] - ERROR: Traceback (most recent call last):
  File "E:\GitHub_rep\test_gateAPI\fishTrade_main20220913.py", line 200, in strategy
    lastOrderPrice,amount,_type=huobi_market.get_last_order_price(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 236, in get_last_order_price
    result = self.get_orders_history(symbol)
  File "E:\GitHub_rep\test_gateAPI\marketHelper1005.py", line 270, in get_orders_history
    result = util.future_api.get_closed_posHistories(symbol)
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 250, in get_closed_posHistories
    return json_operation(r.json())
  File "E:\GitHub_rep\test_gateAPI\util\future_api.py", line 214, in json_operation
    with open('../log/data.json', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../log/data.json'

